"""Generate INDEX.md and commit it, staging only its own generated paths.

Never `git add -A`: this repo lives inside a tree that routinely holds
unrelated work in progress, and a generated commit that swept that up would be
worse than no commit at all.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

from scripts.config import Config, load_config
from scripts.descriptions import Description, load_descriptions, project_key
from scripts.paths import (
    descriptions_path, facts_path, index_path, psum_home, state_dir,
)

from scripts.fsutil import LockBusy, atomic_write, facts_error, read_json, state_lock
from scripts.render_terminal import relative_age

_ENV = {**os.environ, "GIT_OPTIONAL_LOCKS": "0"}

#: Filename of the phone-mountable copy under `state/vault/`. It must contain
#: no whitespace: pvault splits each config line on its first whitespace run,
#: so a vault-path may contain spaces but a SOURCE path may not. Named here
#: rather than inlined so that rule is asserted by a test instead of learned
#: again from a mount that silently truncates at the space.
VAULT_INDEX_NAME = "PORTFOLIO-INDEX.md"

#: Drop everything but word characters, hyphens and spaces, then turn spaces
#: into hyphens -- the same reduction GitHub and Obsidian both apply when they
#: derive a heading's anchor. Consistency with those two renderers matters
#: more than matching either one byte-for-byte in some punctuation corner
#: case: this file's own links are generated by the SAME function, so they
#: always resolve against the headings this module writes.
_ANCHOR_DROP = re.compile(r"[^\w\- ]", re.UNICODE)


def _slugify_heading(text: str) -> str:
    s = re.sub(r"\s+", "-", _ANCHOR_DROP.sub("", text.strip().lower()))
    return s


def build_anchors(projects_in_heading_order: list[dict]) -> dict[str, str]:
    """Map each project's slug to its anchor, in the exact order headings are
    emitted. Two projects can share a display name across categories (e.g.
    `Remote-VS-Code` and `remote-vs-code`) -- the first occurrence keeps the
    bare slug and every later duplicate gets a numeric suffix, the same
    de-duplication GitHub and Obsidian both perform.
    """
    seen: dict[str, int] = {}
    anchors: dict[str, str] = {}
    for p in projects_in_heading_order:
        base = _slugify_heading(_display_name(p))
        n = seen.get(base, 0)
        anchors[p["slug"]] = base if n == 0 else f"{base}-{n}"
        seen[base] = n + 1
    return anchors


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, env=_ENV, timeout=10,
    )


def commit_index(repo: Path, paths: list[Path], message: str) -> bool:
    """Stage exactly `paths` and commit. Return False when there is nothing to do."""
    rels = [str(Path(p).resolve().relative_to(Path(repo).resolve())) for p in paths]
    _git(repo, "add", "--", *rels)
    staged = _git(repo, "diff", "--cached", "--name-only", "--", *rels).stdout.strip()
    if not staged:
        return False
    r = _git(repo, "commit", "-q", "-m", message, "--", *rels)
    return r.returncode == 0


def _display_name(p: dict) -> str:
    """A redacted record's `name` is null (see redact_record in scan.py) — a
    doc-only project promoted purely by discovery can be named after the
    client itself. Every surface that shows a project's name falls back to
    its digest slug rather than assume `name` is always safe to print.
    """
    return p.get("name") or p.get("slug") or "?"


def _description_text(p: dict, descriptions: dict[str, Description] | None, root: Path) -> str:
    if not descriptions:
        return "_No description yet._"
    entry = descriptions.get(project_key(p, root))
    return entry.text if entry and entry.text else "_No description yet._"


def render(
    facts: dict, cfg: Config, *, now: datetime,
    descriptions: dict[str, Description] | None = None,
) -> str:
    projects = facts.get("projects", [])
    root = cfg.settings.root.resolve()

    # Grouping and heading order are computed up front: the Attention and
    # Recent sections link to `#<anchor>`, and the anchor for a given project
    # can only be known once every heading this document will emit -- in the
    # exact order it will emit them -- has been walked once for collisions.
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for p in projects:
        by_cat[p.get("category_display") or p["category"]].append(p)
    heading_order = [
        p for cat in sorted(by_cat) for p in sorted(by_cat[cat], key=_display_name)
    ]
    anchors = build_anchors(heading_order)

    def link(p: dict) -> str:
        return f"[{_display_name(p)}](#{anchors[p['slug']]})"

    lines: list[str] = [
        "# Workspace Portfolio Index",
        "",
        "<!-- GENERATED by `psum index` — edits here are overwritten. -->",
        "",
        f"**Scanned:** {facts['scanned_at']} · "
        f"**{len(projects)} projects** across "
        f"{len({p['category'] for p in projects})} categories",
        "",
    ]

    attention = sorted(
        (p for p in projects if p["derived"]["attention"] > 0),
        key=lambda p: (-p["derived"]["attention"], _display_name(p)),
    )[:15]
    lines += ["## Attention", ""]
    if attention:
        lines += ["| # | Project | Status | Last | Why |", "|---|---|---|---|---|"]
        for p in attention:
            why = "; ".join(p["derived"]["attention_reasons"]) or "—"
            lines.append(
                f"| {p['derived']['attention']} "
                f"| {link(p)} "
                f"| {p['derived']['status']} "
                f"| {relative_age(p['derived']['last_worked'], now)} "
                f"| {why} |"
            )
    else:
        lines.append("Nothing is asking for attention.")
    lines.append("")

    recent = sorted(
        projects, key=lambda p: p["derived"]["last_worked"] or "", reverse=True
    )[:15]
    lines += ["## Recent", "", "| Project | Category | Status | Last |", "|---|---|---|---|"]
    for p in recent:
        lines.append(
            f"| {link(p)} | {p.get('category_display') or p['category']} "
            f"| {p['derived']['status']} "
            f"| {relative_age(p['derived']['last_worked'], now)} |"
        )
    lines.append("")

    lines += ["## All projects", ""]
    for cat in sorted(by_cat):
        lines += [f"### {cat}", ""]
        for p in sorted(by_cat[cat], key=_display_name):
            path = "_redacted_" if p.get("redacted") else f"`{p['display_path']}`"
            lines += [f"#### {_display_name(p)}", ""]
            if p.get("error"):
                lines.append("**! scan error for this project — see state/facts.json**")
                lines.append("")
            lines.append(_description_text(p, descriptions, root))
            lines.append("")
            d = p["derived"]
            lines += [
                f"- Status: {d['status']}",
                f"- Last worked: {relative_age(d['last_worked'], now)}",
                f"- Open items: {d['open_items'] or 0} "
                f"(roadmap: {d.get('roadmap_items') or 0})",
                f"- Attention: {d['attention']}",
                f"- Path: {path}",
                "",
            ]

    if facts.get("errors"):
        lines += ["## Scan errors", ""]
        lines += [
            f"- `{e['path']}` ({e['stage']}): {e['message'] or '(redacted)'}"
            for e in facts["errors"]
        ]
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="psum index")
    ap.add_argument("--no-commit", action="store_true")
    args = ap.parse_args(argv)

    repo = psum_home()
    index = index_path()
    # This copy, never the live INDEX.md: pvault mounts are bidirectional, and
    # Obsidian's normalizer writing back into a file this repo also treats as
    # its own generated output is exactly the corruption this split avoids.
    # Nothing of value lives in state/vault/ -- the next render overwrites it.
    vault_index = state_dir() / "vault" / VAULT_INDEX_NAME
    changed = False
    committed = False
    try:
        with state_lock(state_dir()):
            # Read INSIDE the lock, not before it: a concurrent `scan` writes
            # facts.json under the same lock, and reading it outside gives the
            # render+commit below no guarantee it is working from the facts
            # snapshot its own run started with.
            facts = read_json(facts_path())
            if facts is None:
                print(facts_error(facts_path()), file=sys.stderr)
                return 1
            rendered = render(
                facts, load_config(), now=datetime.now().astimezone(),
                descriptions=load_descriptions(descriptions_path()),
            )
            index_changed = atomic_write(index, rendered)
            vault_changed = atomic_write(vault_index, rendered)
            changed = index_changed or vault_changed
            if changed and not args.no_commit:
                committed = commit_index(
                    repo, [index, vault_index],
                    f"chore(index): {len(facts['projects'])} projects, "
                    f"{facts['scanned_at'][:10]}",
                )
    except LockBusy as exc:
        print(f"psum index: {exc}", file=sys.stderr)
        return 75

    # Report what actually happened, not what was attempted: commit_index's
    # return value used to be discarded, so a commit that silently produced no
    # change (or failed) still printed "INDEX.md updated".
    if not changed:
        print("INDEX.md unchanged")
    elif args.no_commit:
        print("INDEX.md updated (not committed: --no-commit)")
    elif committed:
        print("INDEX.md updated and committed")
    else:
        print("INDEX.md updated but nothing was committed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
