"""The machine-readable vault note: `PORTFOLIO-DATA.md`.

`PORTFOLIO-INDEX.md` is for reading; this is for parsing. Away from this
machine there is no `psum query`, so a phone gets its compact tier here --
the same projection, rendered as delimited rows a reader can scan without
guessing where one project's numbers end and the next begin.

It stays markdown because the vault sync filters everything that is not, and
the rows live in a fenced block because Obsidian then renders them as code,
which is what they are.
"""
from __future__ import annotations

from datetime import datetime

from scripts.paths import VAULT_INDEX_NAME
from scripts.query import compact, select

#: The compact projection minus `slug` and `path`. `path` is meaningless on a
#: phone and is precisely the field redaction exists to suppress -- and a
#: non-redacted `slug` is that same absolute path with the separators
#: swapped, so carrying it would reintroduce through the back door what
#: dropping `path` removes. `name` plus `category` identifies a row uniquely.
COLUMNS = (
    "name", "category", "status", "attention", "last_worked", "age",
    "open", "roadmap", "plans", "dirty", "unpushed", "ahead", "stashes",
    "handoff", "half_plan", "redacted", "reasons",
)


def _cell(value) -> str:
    if isinstance(value, bool):
        return "Y" if value else "-"
    if isinstance(value, list):
        value = "; ".join(str(v) for v in value)
    elif value is None:
        value = ""
    # A stray delimiter would shift every later field by one and silently
    # misattribute every value in the row, so the field count is enforced
    # here rather than trusted.
    return str(value).replace("|", "/").replace("\n", " ")


def _row(c: dict) -> str:
    c = dict(c)
    # A redacted record's name is null; its slug is already a client-free
    # digest, and it is what PORTFOLIO-INDEX.md heads that project's section
    # with -- so the two notes agree and no row is anonymous.
    c["name"] = c.get("name") or c.get("slug") or "?"
    # Date only: `age` already carries the precision, and the time-of-day
    # would cost ~1.3 KB across the whole note for nothing a reader uses.
    c["last_worked"] = (c.get("last_worked") or "")[:10]
    return "|".join(_cell(c.get(col)) for col in COLUMNS)


def render(facts: dict, now: datetime) -> str:
    projects = select(facts.get("projects", []))
    return "\n".join([
        "# Portfolio Data",
        "",
        "<!-- GENERATED by `psum index` — machine-readable companion to "
        f"{VAULT_INDEX_NAME}. Edits here are overwritten. -->",
        "",
        f"**Scanned:** {facts.get('scanned_at')} · "
        f"**{len(projects)} projects**",
        "",
        f"Columns: `{'|'.join(COLUMNS)}`",
        "",
        "```",
        *[_row(compact(p, now)) for p in projects],
        "```",
        "",
    ])
